library(datasets)
data(iris)
summary(iris)
install.packages("dplyr")
library(dplyr)
names(iris)
names(iris)<-tolower(names(iris))
names(iris)
virginica <- filter(iris, species == "virginica")
head(virginica)
tail(virginica)
x <- filter(iris, species == "virginica" & sepal.length > 6)
head(x)
tail(x)
tail(virginica)
y <- subset(iris, species == "virginica" & sepal.length > 6)
head(y)
tail(y)
s <- select(iris, sepal.length, sepal.width, petal.length)
s1 <- select(iris, sepal.length:petal.width)
head(s1,3)
newCol <- mutate(iris, greater.half = sepal.width > 0.5 * sepal.length)
head(newCol)
newcol <- arrange(newCol, petal.width)
head(newcol)
arr <- newCol %>% filter(species == "virginica") %>%
  arrange(sepal.width)
arr[30:35,]
summarise(arr, mean.length = mean(sepal.length, na.rm = TRUE))
      